version: 2.1


orbs:
  aws-cli: circleci/aws-cli@4.0

jobs:
  lint:
    docker:
      - image: cimg/node:18.4
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  deploy:
    docker:
      - image: cimg/node:18.4
    steps:
      - checkout
      # add AWS ssh key
      - add_ssh_keys:
          fingerprints:
            - "43:c4:8c:64:a0:ca:d0:0d:74:52:59:ea:fe:4c:e9:5c"
      
      # install AWS CLI
      - aws-cli/setup
      - setup_remote_docker
      - run:
          name: Build and deploy
          command: |
            docker buildx build --platform linux/amd64 -t udacity-capstone .
            export REMOTE_IMAGE=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/udacity-capstone:latest
            echo "REMOTE_IMAGE is $REMOTE_IMAGE"
            docker tag udacity-capstone:latest ${REMOTE_IMAGE}
            docker push ${REMOTE_REPO}
          



workflows:
  default:
    jobs:
      # - lint
      - deploy
          # requires:
          #   - lint

      